- name: Commit and Push Data
        run: |
          git config --global user.name 'NatGasBot'
          git config --global user.email 'bot@noreply.github.com'
          git add pine_code.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Pine Code" && git push)
